services:
  - type: web
    name: budget-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_flask.py
    envVars:
      - key: ADMIN_USERNAME
        value: MSE3105
      - key: ADMIN_PASSWORD
        value: KHU
      - key: SECRET_KEY
        value: your-secret-key-change-this-in-production



