services:
  - type: web
    name: budget-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_flask.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
